### ISSUE TITLE
TTT EOR Settings broken!

### ISSUE THREAD

**Issue by PeteSavarese** [jkralicky/TTT-End-Round-Music#4]
Hi,

So I LOVE THIS ADDON but its sorta broken. When I disable music from TTT F1 Settings, it doesn't stop playin music, instead it will play the WHOLE MP3, it wont stop when the next round begins, it just keeps going until the Mp3 is done playing.

Also could we move it to be in the main settings tab? I have like 5 tabs already and its too cluttered.

**Comment by kralicky** [comment]
Sorry, I don't support this addon anymore. Feel free to get someone else to work on it and send a pull request.

**Comment by PeteSavarese** [comment]
</3 u did an update 14 days ago, u broke my hear

**Comment by kralicky** [comment]
No I didn't, I merged a pull request created by someone else.

**Comment by ghost** [comment]
@MrUnknownGamer i did fix it at #6 
hahaha 1.5 year later (tbh i got gmod this year)

**Comment by PeteSavarese** [comment]
Thanks but I'm MUCH better at coding. I've recoded this entire thing and many more things on my server. Thanks for the info for others though.

**Comment by Junhaochia** [comment]
really cool xd

**Comment by ghost** [comment]
# since your soo pro at this fix this.
lol, look in google everyone is like how to fix this...
since your soo pro at this fix this i removed my own fix
lol, look in google everyone is like how to fix this...
https://facepunch.com/showthread.php?t=1529038
https://forums.ulyssesmod.net/index.php?topic=6917.70
btw a newbie at coding but atleast i fixed it.

**Comment by CyberAP** [comment]
Who cares about your ego, mate. You didn't fix this issue for a year. And now you're closing a real fix for no reason, lol.
